remote_theme: brunochanrio/material-jekyll-chanrio@2025.03.24
plugins:
- jekyll-remote-theme

title: Mochi Live TV
author: Bruno-chanrio




baseurl: "/Mochi-Live-TV"
color: "#FF7FAC"
accentColor: pink
themeColor: pink
fixedNav: 'true' # true or false
developedby: true

repo: "https://github.com/brunochanrio/Mochi-Live-TV"
github_user: "brunochanrio"
github_repo: "Mochi-Live-TV"

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
